export const LOAD_DATA_CATEGORIES = "LOAD_DATA_CATEGORIES";
export const LOAD_DATA_SUB_CATEGORIES = "LOAD_DATA_SUB_CATEGORIES";
export const LOAD_DATA_USERS = "LOAD_DATA_USERS";
export const LOAD_DATA_ROLE = "LOAD_DATA_ROLE";
export const LOAD_DATA_CARTS = "LOAD_DATA_CARTS";

export const UPDATE_ITEMS_SELECTED = "UPDATE_ITEMS_SELECTED";
export const UPDATE_ITEMS_USERS = "UPDATE_ITEMS_USERS";
export const UPDATE_ITEMS_CATEGORIES = "UPDATE_ITEMS_CATEGORIES";
export const UPDATE_ITEMS_SUB_CATEGORIES = "UPDATE_ITEMS_SUB_CATEGORIES";
export const UPDATE_ITEMS_PRODUCTS = "UPDATE_ITEMS_PRODUCTS";
export const UPDATE_ITEMS_CARTS = "UPDATE_ITEMS_CARTS";

export const REDIRECT = "REDIRECT";
export const REDIRECT_CATEGORY = "REDIRECT_CATEGORY";
export const REDIRECT_SUB_CATEGORY = "REDIRECT_SUB_CATEGORY";
export const REDIRECT_PRODUCTS = "REDIRECT_PRODUCTS";

export const FETCH_DATA = "FETCH_DATA";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";